### ISSUE TITLE
VS2017 installation

### ISSUE THREAD

**Issue by CQPosts** [hrai/OpenInGVim#7]
![image](https://user-images.githubusercontent.com/10655924/62158269-1452d480-b2dd-11e9-9398-5d3b73b3ae4c.png)

VsVim is installed.

**Comment by hrai** [comment]
Can you add more information please?

**Comment by CQPosts** [comment]
Here's the install log.

[dd_VSIXInstaller_20190731092234_0ad4.log](https://github.com/hrai/OpenInGVim/files/3452001/dd_VSIXInstaller_20190731092234_0ad4.log)

**Comment by CQPosts** [comment]
It works fine in 2019.

**Comment by hrai** [comment]
@CQPosts I've updated the extension with the fix. Please get the latest and try again.
